print("Hello world")
print("I am in my ISD class right now")
name=input("Hi there, what is your name?")
print("Hello",name,"How are you?")
number_one=int(input("Give me a number"))
number_two=int(input("Give me another number"))
print(number_one)
print(number_two)
print("The sum of",(number_one)+(number_two))
